import matplotlib.pyplot as plt
import numpy
from wordcloud import WordCloud, STOPWORDS, ImageColorGenerator
import spotipy
from spotipy.oauth2 import SpotifyClientCredentials
from spotipy.oauth2 import SpotifyOAuth
import requests
import base64
import pandas as pd
from bs4 import BeautifulSoup
import urllib.request
import re
#Talal Brek's Contribution
username = '22kx7zq2hwaxl66q3uqjwc2zq'
CLIENT_ID = 'f238edd5fc9e4d1a9f074ee91f9fe017'
CLIENT_SECRET = 'b84ff4eee3ef4199b78c734f39624fcc'
scope = "user-library-read"
top_200 = pd.read_csv("US_Top200_10-10-2020.csv")
genres = dict()
genre_list = list()
genres['RAP'] = 0
genres['OTHER'] =0



"""

"""
top_200_artists = top_200['Artist']

sp = spotipy.Spotify(auth_manager=SpotifyOAuth('f238edd5fc9e4d1a9f074ee91f9fe017','b84ff4eee3ef4199b78c734f39624fcc',scope=scope,redirect_uri = 'https://www.spotify.com/us/account/overview/'))

top_200_artists = top_200['Artist']
for i in top_200_artists:
    artist = sp.search(q = i, type ='artist')
    genre_str = ''
    for genre in artist['artists']['items'][0]['genres']:
        genre_str += genre
        genre_list.append(genre)
    if 'rap' in genre_str:
        genres['RAP'] +=1
        
    else:
        genres['OTHER'] += 1
    artist_list = i.split(' ')
    
    

    

    
    
print(genres)
print(genre_list)
wordcloud_string = ''

wordcloud = WordCloud(width=1600, height=800, max_font_size=200, background_color="black").generate(str(genre_list))
        # plt the image generated by WordCloud class
plt.figure(figsize=(12,10))
plt.imshow(wordcloud)
plt.axis("off")
plt.show()
plt.savefig('TBrek_Genre_WordCloud.png')  


x = list(genres.keys())
y = list(genres.values())
print('x = ', x, 'y = ', y) 
fig, axs = plt.subplots(2)
plt.title("RAP VS OTHER GENRES TOP 200 2020", fontsize=14);
axs[0].pie(x=y, autopct="%.1f%%",  labels=x, pctdistance=0.5)

plt.savefig('tbrek_rap_vs_other_pie.png')
axs[1].bar(x , y,  width = 0.2, color = 'maroon')
plt.xlabel("Genres") 
plt.ylabel("No. of songs") 
plt.show()
#plt.title("RAP VS OTHER GENRES TOP 200 2020", fontsize=14);
plt.savefig('tbrek_rap_vs_other_bar.png')


